# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }

    encoders:
        Lthrt\UserBundle\Entity\User:
            algorithm: bcrypt
            cost: "%bcrypt_cost%"
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        chain_provider:
            chain:
                providers: [ in_memory, lthrt_user_provider  ]
        in_memory:
            memory: 
                users:
                    _lthrt:
                        password: "%lthrt_password%"
                        roles: 'ROLE_DEV'

        lthrt_user_provider:
            entity:
                class: Lthrt\UserBundle\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        local:
            anonymous: ~
            host: localhost
            provider: chain_provider
            form_login:
                check_path: /login
                login_path: /login
            logout:
                path: /logout
                target: /login
            pattern: ^/
        main:
            anonymous: ~
            provider: chain_provider
            form_login:
                check_path: /login
                login_path: /login
            logout:
                path: /logout
                target: /login
            pattern: ^/

     
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_DEV: ROLE_ADMIN

    # acl:
    #     connection: default