<?php

namespace TRBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use TRBundle\Entity\InitialState;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadTRBundleEntityInitialState extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 3;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(InitialState::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new InitialState();
        $item1->eigenfunction=$this->getReference('_reference_TRBundleEntityEigenfunction1');
        $item1->sheep=0;
        $item1->dogs=1;
        $item1->pigs=0;
        $item1->resolved=true;
        $item1->closed=true;
        $item1->triggered=true;
        $item1->id=1;
        $this->addReference('_reference_TRBundleEntityInitialState1', $item1);
        $manager->persist($item1);

        $item2 = new InitialState();
        $item2->eigenfunction=$this->getReference('_reference_TRBundleEntityEigenfunction3');
        $item2->sheep=0;
        $item2->dogs=1;
        $item2->pigs=0;
        $item2->resolved=true;
        $item2->closed=true;
        $item2->triggered=true;
        $item2->id=2;
        $this->addReference('_reference_TRBundleEntityInitialState2', $item2);
        $manager->persist($item2);

        $item3 = new InitialState();
        $item3->eigenfunction=$this->getReference('_reference_TRBundleEntityEigenfunction6');
        $item3->sheep=1;
        $item3->dogs=0;
        $item3->pigs=0;
        $item3->resolved=true;
        $item3->closed=true;
        $item3->triggered=true;
        $item3->id=3;
        $this->addReference('_reference_TRBundleEntityInitialState3', $item3);
        $manager->persist($item3);

        $item4 = new InitialState();
        $item4->eigenfunction=$this->getReference('_reference_TRBundleEntityEigenfunction11');
        $item4->sheep=0;
        $item4->dogs=1;
        $item4->pigs=0;
        $item4->resolved=true;
        $item4->closed=true;
        $item4->triggered=true;
        $item4->id=4;
        $this->addReference('_reference_TRBundleEntityInitialState4', $item4);
        $manager->persist($item4);

        $item5 = new InitialState();
        $item5->eigenfunction=$this->getReference('_reference_TRBundleEntityEigenfunction16');
        $item5->sheep=0;
        $item5->dogs=1;
        $item5->pigs=0;
        $item5->resolved=true;
        $item5->closed=true;
        $item5->triggered=true;
        $item5->id=5;
        $this->addReference('_reference_TRBundleEntityInitialState5', $item5);
        $manager->persist($item5);

        $item6 = new InitialState();
        $item6->eigenfunction=$this->getReference('_reference_TRBundleEntityEigenfunction19');
        $item6->sheep=0;
        $item6->dogs=1;
        $item6->pigs=0;
        $item6->resolved=true;
        $item6->closed=true;
        $item6->triggered=true;
        $item6->id=6;
        $this->addReference('_reference_TRBundleEntityInitialState6', $item6);
        $manager->persist($item6);

        $item7 = new InitialState();
        $item7->eigenfunction=$this->getReference('_reference_TRBundleEntityEigenfunction23');
        $item7->sheep=0;
        $item7->dogs=1;
        $item7->pigs=0;
        $item7->resolved=true;
        $item7->closed=true;
        $item7->triggered=true;
        $item7->id=7;
        $this->addReference('_reference_TRBundleEntityInitialState7', $item7);
        $manager->persist($item7);

        $item8 = new InitialState();
        $item8->eigenfunction=$this->getReference('_reference_TRBundleEntityEigenfunction33');
        $item8->sheep=0;
        $item8->dogs=1;
        $item8->pigs=0;
        $item8->resolved=true;
        $item8->closed=false;
        $item8->triggered=false;
        $item8->id=8;
        $this->addReference('_reference_TRBundleEntityInitialState8', $item8);
        $manager->persist($item8);

    
        $manager->flush();
    }

}
