<?php

namespace TRBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use TRBundle\Entity\Mission;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadTRBundleEntityMission extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 1;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(Mission::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new Mission();
        $item1->lambs=2;
        $item1->puppies=0;
        $item1->piglets=0;
        $item1->sheep=6;
        $item1->dogs=0;
        $item1->pigs=0;
        $item1->id=1;
        $item1->name="Pacifist";
        $this->addReference('_reference_TRBundleEntityMission1', $item1);
        $manager->persist($item1);

        $item2 = new Mission();
        $item2->lambs=0;
        $item2->puppies=2;
        $item2->piglets=0;
        $item2->sheep=0;
        $item2->dogs=6;
        $item2->pigs=0;
        $item2->id=2;
        $item2->name="Imperialist";
        $this->addReference('_reference_TRBundleEntityMission2', $item2);
        $manager->persist($item2);

        $item3 = new Mission();
        $item3->lambs=0;
        $item3->puppies=0;
        $item3->piglets=1;
        $item3->sheep=0;
        $item3->dogs=0;
        $item3->pigs=3;
        $item3->id=3;
        $item3->name="";
        $this->addReference('_reference_TRBundleEntityMission3', $item3);
        $manager->persist($item3);

    
        $manager->flush();
    }

}
