<?php

namespace TRBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use TRBundle\Entity\Wave;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadTRBundleEntityWave extends AbstractFixture implements OrderedFixtureInterface
{
    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 1;
    }

    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(Wave::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $item1              = new Wave();
        $item1->position    = 0;
        $item1->align       = 0;
        $item1->description = "Sinking the Lusitania";
        $item1->id          = 1;
        $this->addReference('_reference_TRBundleEntityWave1', $item1);
        $manager->persist($item1);

        $item2              = new Wave();
        $item2->position    = 1;
        $item2->align       = 0;
        $item2->description = "Treaty of Versailles";
        $item2->id          = 2;
        $this->addReference('_reference_TRBundleEntityWave2', $item2);
        $manager->persist($item2);

        $item3              = new Wave();
        $item3->position    = 2;
        $item3->align       = 0;
        $item3->description = "Weimar Economy";
        $item3->id          = 3;
        $this->addReference('_reference_TRBundleEntityWave3', $item3);
        $manager->persist($item3);

        $item4              = new Wave();
        $item4->position    = 3;
        $item4->align       = 0;
        $item4->description = "German Recovery";
        $item4->id          = 4;
        $this->addReference('_reference_TRBundleEntityWave4', $item4);
        $manager->persist($item4);

        $item5              = new Wave();
        $item5->position    = 4;
        $item5->align       = 1;
        $item5->description = "The Russo-German Alliance";
        $item5->id          = 5;
        $this->addReference('_reference_TRBundleEntityWave5', $item5);
        $manager->persist($item5);

        $item6              = new Wave();
        $item6->position    = 5;
        $item6->align       = -1;
        $item6->description = "The Nippo-German Alliance";
        $item6->id          = 6;
        $this->addReference('_reference_TRBundleEntityWave6', $item6);
        $manager->persist($item6);

        $item7              = new Wave();
        $item7->position    = 6;
        $item7->align       = 0;
        $item7->description = "WW II Ends";
        $item7->id          = 7;
        $this->addReference('_reference_TRBundleEntityWave7', $item7);
        $manager->persist($item7);

        $item8              = new Wave();
        $item8->position    = 7;
        $item8->align       = 0;
        $item8->description = "German Atomics";
        $item8->id          = 8;
        $this->addReference('_reference_TRBundleEntityWave8', $item8);
        $manager->persist($item8);

        $item9              = new Wave();
        $item9->position    = 8;
        $item9->align       = -1;
        $item9->description = "US Hegemony";
        $item9->id          = 9;
        $this->addReference('_reference_TRBundleEntityWave9', $item9);
        $manager->persist($item9);

        $item10              = new Wave();
        $item10->position    = 9;
        $item10->align       = 1;
        $item10->description = "The German Cold War";
        $item10->id          = 10;
        $this->addReference('_reference_TRBundleEntityWave10', $item10);
        $manager->persist($item10);

        $item11              = new Wave();
        $item11->position    = 10;
        $item11->align       = 0;
        $item11->description = "The Succession";
        $item11->id          = 11;
        $this->addReference('_reference_TRBundleEntityWave11', $item11);
        $manager->persist($item11);

        $manager->flush();
    }
}
