<?php

namespace TRBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use TRBundle\Entity\Game;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadTRBundleEntityGame extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 1;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(Game::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new Game();
        $item1->description="TestData";
        $item1->id=1;
        $this->addReference('_reference_TRBundleEntityGame1', $item1);
        $manager->persist($item1);

    
        $manager->flush();
    }

}
