<?php

namespace TRBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use TRBundle\Entity\State;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadTRBundleEntityState extends AbstractFixture implements OrderedFixtureInterface
{
    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 3;
    }

    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(State::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $item2                = new State();
        $item2->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item2->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction18');
        $item2->sheep         = 0;
        $item2->dogs          = 0;
        $item2->pigs          = 0;
        $item2->resolved      = false;
        $item2->closed        = true;
        $item2->triggered     = true;

        $item2->id = 2;
        $this->addReference('_reference_TRBundleEntityState2', $item2);
        $manager->persist($item2);

        $item3                = new State();
        $item3->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item3->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction10');
        $item3->sheep         = 0;
        $item3->dogs          = 0;
        $item3->pigs          = 0;
        $item3->resolved      = false;
        $item3->closed        = true;
        $item3->triggered     = true;

        $item3->id = 3;
        $this->addReference('_reference_TRBundleEntityState3', $item3);
        $manager->persist($item3);

        $item5                = new State();
        $item5->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item5->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction12');
        $item5->sheep         = 0;
        $item5->dogs          = 0;
        $item5->pigs          = 0;
        $item5->resolved      = false;
        $item5->closed        = true;
        $item5->triggered     = true;

        $item5->id = 5;
        $this->addReference('_reference_TRBundleEntityState5', $item5);
        $manager->persist($item5);

        $item6                = new State();
        $item6->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item6->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction14');
        $item6->sheep         = 0;
        $item6->dogs          = 0;
        $item6->pigs          = 0;
        $item6->resolved      = false;
        $item6->closed        = true;
        $item6->triggered     = true;

        $item6->id = 6;
        $this->addReference('_reference_TRBundleEntityState6', $item6);
        $manager->persist($item6);

        $item7                = new State();
        $item7->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item7->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction30');
        $item7->sheep         = 0;
        $item7->dogs          = 0;
        $item7->pigs          = 0;
        $item7->resolved      = false;
        $item7->closed        = true;
        $item7->triggered     = true;

        $item7->id = 7;
        $this->addReference('_reference_TRBundleEntityState7', $item7);
        $manager->persist($item7);

        $item8                = new State();
        $item8->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item8->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction28');
        $item8->sheep         = 0;
        $item8->dogs          = 0;
        $item8->pigs          = 0;
        $item8->resolved      = false;
        $item8->closed        = true;
        $item8->triggered     = true;

        $item8->id = 8;
        $this->addReference('_reference_TRBundleEntityState8', $item8);
        $manager->persist($item8);

        $item9                = new State();
        $item9->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item9->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction29');
        $item9->sheep         = 0;
        $item9->dogs          = 0;
        $item9->pigs          = 0;
        $item9->resolved      = false;
        $item9->closed        = true;
        $item9->triggered     = true;

        $item9->id = 9;
        $this->addReference('_reference_TRBundleEntityState9', $item9);
        $manager->persist($item9);

        $item11                = new State();
        $item11->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item11->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction31');
        $item11->sheep         = 0;
        $item11->dogs          = 0;
        $item11->pigs          = 0;
        $item11->resolved      = false;
        $item11->closed        = true;
        $item11->triggered     = true;

        $item11->id = 11;
        $this->addReference('_reference_TRBundleEntityState11', $item11);
        $manager->persist($item11);

        $item12                = new State();
        $item12->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item12->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction32');
        $item12->sheep         = 0;
        $item12->dogs          = 0;
        $item12->pigs          = 0;
        $item12->resolved      = false;
        $item12->closed        = true;
        $item12->triggered     = true;

        $item12->id = 12;
        $this->addReference('_reference_TRBundleEntityState12', $item12);
        $manager->persist($item12);

        $item13                = new State();
        $item13->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item13->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction26');
        $item13->sheep         = 0;
        $item13->dogs          = 0;
        $item13->pigs          = 0;
        $item13->resolved      = false;
        $item13->closed        = true;
        $item13->triggered     = true;

        $item13->id = 13;
        $this->addReference('_reference_TRBundleEntityState13', $item13);
        $manager->persist($item13);

        $item14                = new State();
        $item14->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item14->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction4');
        $item14->sheep         = 0;
        $item14->dogs          = 0;
        $item14->pigs          = 0;
        $item14->resolved      = false;
        $item14->closed        = true;
        $item14->triggered     = true;

        $item14->id = 14;
        $this->addReference('_reference_TRBundleEntityState14', $item14);
        $manager->persist($item14);

        $item16                = new State();
        $item16->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item16->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction5');
        $item16->sheep         = 0;
        $item16->dogs          = 0;
        $item16->pigs          = 0;
        $item16->resolved      = false;
        $item16->closed        = true;
        $item16->triggered     = true;

        $item16->id = 16;
        $this->addReference('_reference_TRBundleEntityState16', $item16);
        $manager->persist($item16);

        $item17                = new State();
        $item17->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item17->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction21');
        $item17->sheep         = 0;
        $item17->dogs          = 0;
        $item17->pigs          = 0;
        $item17->resolved      = false;
        $item17->closed        = true;
        $item17->triggered     = true;

        $item17->id = 17;
        $this->addReference('_reference_TRBundleEntityState17', $item17);
        $manager->persist($item17);

        $item18                = new State();
        $item18->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item18->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction27');
        $item18->sheep         = 0;
        $item18->dogs          = 0;
        $item18->pigs          = 0;
        $item18->resolved      = false;
        $item18->closed        = true;
        $item18->triggered     = true;

        $item18->id = 18;
        $this->addReference('_reference_TRBundleEntityState18', $item18);
        $manager->persist($item18);

        $item19                = new State();
        $item19->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item19->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction24');
        $item19->sheep         = 0;
        $item19->dogs          = 0;
        $item19->pigs          = 0;
        $item19->resolved      = false;
        $item19->closed        = true;
        $item19->triggered     = true;

        $item19->id = 19;
        $this->addReference('_reference_TRBundleEntityState19', $item19);
        $manager->persist($item19);

        $item20                = new State();
        $item20->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item20->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction25');
        $item20->sheep         = 0;
        $item20->dogs          = 0;
        $item20->pigs          = 0;
        $item20->resolved      = false;
        $item20->closed        = true;
        $item20->triggered     = true;

        $item20->id = 20;
        $this->addReference('_reference_TRBundleEntityState20', $item20);
        $manager->persist($item20);

        $item21                = new State();
        $item21->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item21->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction20');
        $item21->sheep         = 0;
        $item21->dogs          = 0;
        $item21->pigs          = 0;
        $item21->resolved      = false;
        $item21->closed        = true;
        $item21->triggered     = true;

        $item21->id = 21;
        $this->addReference('_reference_TRBundleEntityState21', $item21);
        $manager->persist($item21);

        $item22                = new State();
        $item22->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item22->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction22');
        $item22->sheep         = 0;
        $item22->dogs          = 0;
        $item22->pigs          = 0;
        $item22->resolved      = false;
        $item22->closed        = true;
        $item22->triggered     = true;

        $item22->id = 22;
        $this->addReference('_reference_TRBundleEntityState22', $item22);
        $manager->persist($item22);

        $item25                = new State();
        $item25->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item25->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction2');
        $item25->sheep         = 0;
        $item25->dogs          = 0;
        $item25->pigs          = 0;
        $item25->resolved      = false;
        $item25->closed        = true;
        $item25->triggered     = true;
        $item25->id            = 25;
        $this->addReference('_reference_TRBundleEntityState25', $item25);
        $manager->persist($item25);

        $item26                = new State();
        $item26->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item26->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction7');
        $item26->sheep         = 0;
        $item26->dogs          = 0;
        $item26->pigs          = 0;
        $item26->resolved      = false;
        $item26->closed        = true;
        $item26->triggered     = true;

        $item26->id = 26;
        $this->addReference('_reference_TRBundleEntityState26', $item26);
        $manager->persist($item26);

        $item27                = new State();
        $item27->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item27->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction9');
        $item27->sheep         = 0;
        $item27->dogs          = 0;
        $item27->pigs          = 0;
        $item27->resolved      = false;
        $item27->closed        = true;
        $item27->triggered     = true;

        $item27->id = 27;
        $this->addReference('_reference_TRBundleEntityState27', $item27);
        $manager->persist($item27);

        $item28                = new State();
        $item28->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item28->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction8');
        $item28->sheep         = 0;
        $item28->dogs          = 0;
        $item28->pigs          = 0;
        $item28->resolved      = false;
        $item28->closed        = true;
        $item28->triggered     = true;

        $item28->id = 28;
        $this->addReference('_reference_TRBundleEntityState28', $item28);
        $manager->persist($item28);

        $item31                = new State();
        $item31->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item31->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction15');
        $item31->sheep         = 0;
        $item31->dogs          = 0;
        $item31->pigs          = 0;
        $item31->resolved      = false;
        $item31->closed        = true;
        $item31->triggered     = true;

        $item31->id = 31;
        $this->addReference('_reference_TRBundleEntityState31', $item31);
        $manager->persist($item31);

        $item32                = new State();
        $item32->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item32->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction13');
        $item32->sheep         = 0;
        $item32->dogs          = 0;
        $item32->pigs          = 0;
        $item32->resolved      = false;
        $item32->closed        = true;
        $item32->triggered     = true;

        $item32->id = 32;
        $this->addReference('_reference_TRBundleEntityState32', $item32);
        $manager->persist($item32);

        $item33                = new State();
        $item33->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item33->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction17');
        $item33->sheep         = 0;
        $item33->dogs          = 0;
        $item33->pigs          = 0;
        $item33->resolved      = false;
        $item33->closed        = true;
        $item33->triggered     = true;

        $item33->id = 33;
        $this->addReference('_reference_TRBundleEntityState33', $item33);
        $manager->persist($item33);

        $item1                = new State();
        $item1->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item1->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction11');
        $item1->sheep         = 0;
        $item1->dogs          = 1;
        $item1->pigs          = 0;
        $item1->resolved      = true;
        $item1->closed        = false;
        $item1->triggered     = false;

        $item1->id = 1;
        $this->addReference('_reference_TRBundleEntityState1', $item1);
        $manager->persist($item1);

        $item4                = new State();
        $item4->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item4->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction19');
        $item4->sheep         = 0;
        $item4->dogs          = 1;
        $item4->pigs          = 0;
        $item4->resolved      = true;
        $item4->closed        = false;
        $item4->triggered     = false;

        $item4->id = 4;
        $this->addReference('_reference_TRBundleEntityState4', $item4);
        $manager->persist($item4);

        $item10                = new State();
        $item10->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item10->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction3');
        $item10->sheep         = 0;
        $item10->dogs          = 1;
        $item10->pigs          = 0;
        $item10->resolved      = true;
        $item10->closed        = false;
        $item10->triggered     = false;

        $item10->id = 10;
        $this->addReference('_reference_TRBundleEntityState10', $item10);
        $manager->persist($item10);

        $item15                = new State();
        $item15->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item15->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction33');
        $item15->sheep         = 0;
        $item15->dogs          = 1;
        $item15->pigs          = 0;
        $item15->resolved      = true;
        $item15->closed        = false;
        $item15->triggered     = false;

        $item15->id = 15;
        $this->addReference('_reference_TRBundleEntityState15', $item15);
        $manager->persist($item15);

        $item23                = new State();
        $item23->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item23->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction23');
        $item23->sheep         = 0;
        $item23->dogs          = 1;
        $item23->pigs          = 0;
        $item23->resolved      = true;
        $item23->closed        = false;
        $item23->triggered     = false;

        $item23->id = 23;
        $this->addReference('_reference_TRBundleEntityState23', $item23);
        $manager->persist($item23);

        $item24                = new State();
        $item24->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item24->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction1');
        $item24->sheep         = 0;
        $item24->dogs          = 1;
        $item24->pigs          = 0;
        $item24->resolved      = true;
        $item24->closed        = false;
        $item24->triggered     = false;
        $item24->id            = 24;
        $this->addReference('_reference_TRBundleEntityState24', $item24);
        $manager->persist($item24);

        $item30                = new State();
        $item30->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item30->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction16');
        $item30->sheep         = 0;
        $item30->dogs          = 1;
        $item30->pigs          = 0;
        $item30->resolved      = true;
        $item30->closed        = false;
        $item30->triggered     = false;

        $item30->id = 30;
        $this->addReference('_reference_TRBundleEntityState30', $item30);
        $manager->persist($item30);

        $item29                = new State();
        $item29->game          = $this->getReference('_reference_TRBundleEntityGame1');
        $item29->eigenfunction = $this->getReference('_reference_TRBundleEntityEigenfunction6');
        $item29->sheep         = 1;
        $item29->dogs          = 0;
        $item29->pigs          = 0;
        $item29->resolved      = true;
        $item29->closed        = false;
        $item29->triggered     = false;

        $item29->id = 29;
        $this->addReference('_reference_TRBundleEntityState29', $item29);
        $manager->persist($item29);
        $manager->flush();

        $item2->prev = [
            $this->getReference('_reference_TRBundleEntityState6'),
            $this->getReference('_reference_TRBundleEntityState32'),
        ];
        $item3->prev = [
            $this->getReference('_reference_TRBundleEntityState29'),
        ];
        $item5->prev = [
            $this->getReference('_reference_TRBundleEntityState26'),
            $this->getReference('_reference_TRBundleEntityState28'),
        ];
        $item6->prev = [
            $this->getReference('_reference_TRBundleEntityState27'),
        ];
        $item7->prev = [
            $this->getReference('_reference_TRBundleEntityState19'),
        ];
        $item8->prev = [
            $this->getReference('_reference_TRBundleEntityState19'),
        ];
        $item9->prev = [
            $this->getReference('_reference_TRBundleEntityState19'),
        ];
        $item11->prev = [
            $this->getReference('_reference_TRBundleEntityState19'),
        ];
        $item12->prev = [
            $this->getReference('_reference_TRBundleEntityState7'),
            $this->getReference('_reference_TRBundleEntityState8'),
            $this->getReference('_reference_TRBundleEntityState9'),
        ];
        $item13->prev = [
            $this->getReference('_reference_TRBundleEntityState20'),
        ];
        $item14->prev = [
            $this->getReference('_reference_TRBundleEntityState25'),
        ];
        $item16->prev = [
            $this->getReference('_reference_TRBundleEntityState25'),
            $this->getReference('_reference_TRBundleEntityState24'),
        ];
        $item17->prev = [
            $this->getReference('_reference_TRBundleEntityState2'),
            $this->getReference('_reference_TRBundleEntityState31'),
            $this->getReference('_reference_TRBundleEntityState33'),
        ];
        $item18->prev = [
            $this->getReference('_reference_TRBundleEntityState20'),
        ];
        $item19->prev = [
            $this->getReference('_reference_TRBundleEntityState17'),
            $this->getReference('_reference_TRBundleEntityState21'),
            $this->getReference('_reference_TRBundleEntityState22'),
        ];
        $item20->prev = [
            $this->getReference('_reference_TRBundleEntityState17'),
            $this->getReference('_reference_TRBundleEntityState21'),
            $this->getReference('_reference_TRBundleEntityState22'),
        ];
        $item21->prev = [
            $this->getReference('_reference_TRBundleEntityState33'),
        ];
        $item22->prev = [
            $this->getReference('_reference_TRBundleEntityState2'),
            $this->getReference('_reference_TRBundleEntityState31'),
            $this->getReference('_reference_TRBundleEntityState4'),
            $this->getReference('_reference_TRBundleEntityState30'),
        ];
        $item26->prev = [
            $this->getReference('_reference_TRBundleEntityState16'),
            $this->getReference('_reference_TRBundleEntityState10'),
        ];
        $item27->prev = [
            $this->getReference('_reference_TRBundleEntityState14'),
        ];
        $item28->prev = [
            $this->getReference('_reference_TRBundleEntityState14'),
            $this->getReference('_reference_TRBundleEntityState16'),
        ];
        $item31->prev = [
            $this->getReference('_reference_TRBundleEntityState3'),
            $this->getReference('_reference_TRBundleEntityState32'),
        ];
        $item32->prev = [
            $this->getReference('_reference_TRBundleEntityState27'),
            $this->getReference('_reference_TRBundleEntityState28'),
        ];
        $item33->prev = [
            $this->getReference('_reference_TRBundleEntityState6'),
            $this->getReference('_reference_TRBundleEntityState1'),
        ];
        $item1->prev = [
            $this->getReference('_reference_TRBundleEntityState26'),
            $this->getReference('_reference_TRBundleEntityState29'),
        ];
        $item4->prev = [
            $this->getReference('_reference_TRBundleEntityState3'),
            $this->getReference('_reference_TRBundleEntityState5'),
            $this->getReference('_reference_TRBundleEntityState1'),
        ];
        $item10->prev = [
            $this->getReference('_reference_TRBundleEntityState24'),
        ];
        $item15->prev = [
            $this->getReference('_reference_TRBundleEntityState7'),
            $this->getReference('_reference_TRBundleEntityState8'),
            $this->getReference('_reference_TRBundleEntityState9'),
            $this->getReference('_reference_TRBundleEntityState11'),
            $this->getReference('_reference_TRBundleEntityState13'),
            $this->getReference('_reference_TRBundleEntityState18'),
            $this->getReference('_reference_TRBundleEntityState23'),
        ];
        $item23->prev = [
            $this->getReference('_reference_TRBundleEntityState2'),
            $this->getReference('_reference_TRBundleEntityState4'),
            $this->getReference('_reference_TRBundleEntityState30'),
        ];
        $item30->prev = [
            $this->getReference('_reference_TRBundleEntityState5'),
            $this->getReference('_reference_TRBundleEntityState1'),
        ];
        $item29->prev = [
            $this->getReference('_reference_TRBundleEntityState10'),
        ];

        $manager->flush();
    }
}
